"""initial

Revision ID: 99952930d94b
Revises: 
Create Date: 2026-09-10 13:48:56.111263

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99952930d94b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('entry_no', sa.String(length=64), nullable=False),
    sa.Column('file_no', sa.String(length=64), nullable=True),
    sa.Column('owner_full_name', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('legal_description', sa.Text(), nullable=True),
    sa.Column('r_number', sa.String(length=32), nullable=True),
    sa.Column('instrument_number', sa.String(length=64), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('original_loan_amount', sa.Float(), nullable=True),
    sa.Column('loan_origination_date', sa.Date(), nullable=True),
    sa.Column('loan_type', sa.String(length=64), nullable=True),
    sa.Column('lender', sa.String(length=256), nullable=True),
    sa.Column('servicer', sa.String(length=256), nullable=True),
    sa.Column('trustee', sa.String(length=256), nullable=True),
    sa.Column('county', sa.String(length=64), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('source_file_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_purchase_money', sa.Boolean(), nullable=True),
    sa.Column('has_hoa_rider', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('entry_no')
    )
    op.create_table('loan_estimates',
    sa.Column('entry_no', sa.String(length=64), nullable=False),
    sa.Column('months_elapsed', sa.Integer(), nullable=True),
    sa.Column('assumed_rate', sa.Float(), nullable=True),
    sa.Column('est_monthly_payment', sa.Float(), nullable=True),
    sa.Column('est_principal_paid', sa.Float(), nullable=True),
    sa.Column('est_interest_paid', sa.Float(), nullable=True),
    sa.Column('est_remaining_balance', sa.Float(), nullable=True),
    sa.Column('est_pct_paid_down', sa.Float(), nullable=True),
    sa.Column('filter_flag', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['entry_no'], ['properties.entry_no'], ),
    sa.PrimaryKeyConstraint('entry_no')
    )
    op.create_table('step_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_no', sa.String(length=64), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_file_path', sa.Text(), nullable=True),
    sa.Column('extracted_json', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_no'], ['properties.entry_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_results')
    op.drop_table('loan_estimates')
    op.drop_table('properties')
    # ### end Alembic commands ###
